### ISSUE TITLE
手動出席欠席のdropmenuがおかしい

### ISSUE THREAD

**Issue by batapii** [N3AttendanceManager/AttendanceApp#11]
|<img width="340" src="https://github.com/N3AttendanceManager/AttendanceApp/assets/97936349/af3d24df-2197-4e38-96cb-4fac7f64c6e9">

**Comment by batapii** [comment]
@yuchan2215 
どこらへんが悪さしてそうですか

**Comment by yuchan2215** [comment]
<img width="980" alt="image" src="https://github.com/N3AttendanceManager/AttendanceApp/assets/38094366/596426aa-0a5e-4635-a9ad-af27de9cc1c5">
なおったヨ
